### ISSUE TITLE
argocd

### ISSUE THREAD

**Issue by jinleileiking** [jinleileiking/learning-notes#21]
> git 同步不了

如果仓库太大，需要

```
 ked argocd-repo-server

      automountServiceAccountToken: false
      containers:
      - args:
        - /usr/local/bin/argocd-repo-server
        env:
        - name: ARGOCD_EXEC_TIMEOUT
          value: 10m

```

> 私有gitlab

用deploytoken，别用pass，user，直接url就行：`https://gitlab+deploy-token-5:PPPPPWWWWWWWW@git.v.com:22443/cloud/cicd.git`
